In [1]:
import os
import json
import numpy as np
import pathlib
from tqdm import tqdm
import shutil

In [2]:
keypoint_root_folder_path = "C:/ict_sign_language_project01/data/keypoint"
keypoint_folder_path_list = os.listdir(keypoint_root_folder_path)
keypoint_folder_path_list

['NIA_SL_G1_EARTHQUAKE000013_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000014_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000015_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000016_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000017_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000018_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000019_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000023_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000024_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000025_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000027_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000029_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000030_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000032_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000033_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000036_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000037_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000038_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000039_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000040_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000043_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000046_1_CRO

In [3]:
for keypoint_folder_path in keypoint_folder_path_list[0:2]:
    print("=" * 100)
    print("keypoint_folder_path=", keypoint_folder_path)
    print("=" * 100)

    json_file_folder = keypoint_root_folder_path + "/" + keypoint_folder_path

    #json_file_folder에 저장된 JSON 파일 리스트 리턴
    json_file_list = os.listdir(json_file_folder)
    json_num = len(json_file_list)

    for i in range(1):
        json_file_path = f"{json_file_folder}/{keypoint_folder_path}_{i}_keypoints.json"

        with open(json_file_path, "r") as keypoint_json_file:
            #키포인트가 저장된 JSON 파일의 내용 리턴
            keypoint_json = json.load(keypoint_json_file)
            
            #포즈, 왼손, 오른손의 키포인트 리턴
            pose_keypoints_2d = keypoint_json["people"][0]["pose_keypoints_2d"]
            hand_left_keypoints_2d = keypoint_json["people"][0]["hand_left_keypoints_2d"]
            hand_right_keypoints_2d = keypoint_json["people"][0]["hand_right_keypoints_2d"]

            #포즈의 키포인트가 저장된 리스트를 numpy 배열로 변환
            #리스트를 3열로 변환하고 행은 생략
            pose_keypoint_arr = np.array(pose_keypoints_2d).reshape(-1, 3)
            hand_left_keypoint_arr = np.array(hand_left_keypoints_2d).reshape(-1, 3)
            hand_right_keypoint_arr = np.array(hand_right_keypoints_2d).reshape(-1, 3)
            print("pose_keypoint_arr=", pose_keypoint_arr)
            print("=" * 100)

            #키포인트의 x, y좌표 리턴(모든 행, 2열 미만)
            print("pose_keypoint_arr[: , 0:2]=", pose_keypoint_arr[: , :2])
            
            #포즈, 왼손, 오른손 키포인트의 x, y좌표 배열들을 합쳐 새로운 키포인트 배열 생성
            keypoint_arr = np.concatenate((pose_keypoint_arr[:, :2], hand_left_keypoint_arr[:, :2], hand_right_keypoint_arr[:, :2]))
            print("keypoint_arr=", keypoint_arr)
            print("=" * 100)
            

keypoint_folder_path= NIA_SL_G1_EARTHQUAKE000013_1_CROWD1079481
pose_keypoint_arr= [[9.54064e+02 3.39052e+02 9.55243e-01]
 [9.51032e+02 4.83329e+02 8.50091e-01]
 [8.36434e+02 4.83270e+02 7.93700e-01]
 [7.98093e+02 6.68518e+02 6.86232e-01]
 [8.06837e+02 8.51065e+02 7.90022e-01]
 [1.05421e+03 4.83252e+02 7.80045e-01]
 [1.09254e+03 6.71463e+02 7.99208e-01]
 [1.10713e+03 8.42299e+02 7.64755e-01]
 [9.53997e+02 8.48173e+02 6.03028e-01]
 [8.80423e+02 8.54012e+02 5.81586e-01]
 [8.86466e+02 1.07486e+03 2.61158e-01]
 [0.00000e+00 0.00000e+00 0.00000e+00]
 [1.02480e+03 8.54018e+02 5.79183e-01]
 [1.02767e+03 1.07486e+03 3.25513e-01]
 [0.00000e+00 0.00000e+00 0.00000e+00]
 [9.30534e+02 3.15328e+02 9.67228e-01]
 [9.80626e+02 3.18235e+02 9.19988e-01]
 [9.01040e+02 3.33143e+02 8.23626e-01]
 [1.01889e+03 3.44906e+02 8.54513e-01]
 [0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.0000

In [4]:
#배열을 저장할 폴더
save_root_path = f"data/keypoint_arr/"

#배열을 저장할 폴더의 정보를 알아낼 객체 리턴
arr_save_path = pathlib.Path(save_root_path)

if arr_save_path.exists():
    shutil.rmtree(save_root_path)

os.makedirs(save_root_path)

In [5]:
keypoint_folder_path_list

['NIA_SL_G1_EARTHQUAKE000013_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000014_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000015_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000016_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000017_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000018_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000019_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000023_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000024_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000025_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000027_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000029_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000030_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000032_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000033_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000036_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000037_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000038_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000039_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000040_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000043_1_CROWD1079481',
 'NIA_SL_G1_EARTHQUAKE000046_1_CRO

In [6]:
for keypoint_folder_path in tqdm(keypoint_folder_path_list):
    json_file_folder = keypoint_root_folder_path + "/" + keypoint_folder_path
    json_file_list = os.listdir(json_file_folder)
    json_num = len(json_file_list)
    
    #JSON 파일의 내용을 저장할 리스트
    all_keypoint_list = []
    
    for i in range(json_num):
        json_file_path = f"{json_file_folder}/{keypoint_folder_path}_{i}_keypoints.json"
        
        with open(json_file_path, "r") as keypoint_json_file:
            #키포인트가 저장된 JSON 파일의 내용 리턴
            keypoint_json = json.load(keypoint_json_file)
            #포즈, 왼손, 오른손 키포인트 리턴
            pose_keypoints_2d = keypoint_json["people"][0]["pose_keypoints_2d"]
            hand_left_keypoints_2d = keypoint_json["people"][0]["hand_left_keypoints_2d"]
            hand_right_keypoints_2d = keypoint_json["people"][0]["hand_right_keypoints_2d"]

            #리스트를 numpy 배열로 변환(행은 생략, 3열)
            pose_keypoint_arr = np.array(pose_keypoints_2d).reshape(-1, 3)
            hand_left_keypoint_arr = np.array(hand_left_keypoints_2d).reshape(-1, 3)
            hand_right_keypoint_arr = np.array(hand_right_keypoints_2d).reshape(-1, 3)
            
            #각 배열들의 x, y좌표를 합쳐 새로운 배열 생성
            keypoint_arr = np.concatenate((pose_keypoint_arr[:, :2], hand_left_keypoint_arr[:, :2], hand_right_keypoint_arr[:, :2]))
            
            #keypoint_arr을 all_keypoint_list에 추가
            all_keypoint_list.append(keypoint_arr.tolist())

    #all_keypoint_list를 실수타입 배열로 변환
    all_keypoint_arr = np.array(all_keypoint_list, dtype="float32")

    if keypoint_folder_path[-1]=='F':
        #all_keypoint_arr을 data.keypoint_arr 폴더에 저장
        np.save(f"{save_root_path}/{keypoint_folder_path[:-2]}", all_keypoint_arr)
    else:
        #all_keypoint_arr을 data.keypoint_arr 폴더에 저장
        np.save(f"{save_root_path}/{keypoint_folder_path}", all_keypoint_arr)

100%|████████████████████████████████████████████████████████████████████████████████| 352/352 [00:25<00:00, 13.54it/s]
